# Generated by Django 3.2.7 on 2021-10-12 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='container',
        ),
        migrations.RemoveField(
            model_name='product',
            name='how_to_use',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_important',
        ),
        migrations.RemoveField(
            model_name='product',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='product',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='storage_conditions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_hair',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_skin',
        ),
    ]
