# Generated by Django 3.2.7 on 2021-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_product_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='container',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='Тара/упаковка'),
        ),
        migrations.AddField(
            model_name='product',
            name='how_to_use',
            field=models.TextField(blank=True, null=True, verbose_name='Способ применения'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендация'),
        ),
        migrations.AddField(
            model_name='product',
            name='storage_conditions',
            field=models.TextField(blank=True, null=True, verbose_name='Условия хранения'),
        ),
    ]
