# Generated by Django 3.2.7 on 2021-10-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20211012_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='problems',
            field=models.ManyToManyField(blank=True, to='mainapp.Problem', verbose_name='Проблема кожи лица (ТОЛЬКО ДЛЯ ЛИЦА)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.ManyToManyField(blank=True, to='mainapp.Purpose', verbose_name='Назначение (ТОЛЬКО ДЛЯ ТЕЛА)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, to='mainapp.Size', verbose_name='Объем/вес'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_hair',
            field=models.ManyToManyField(blank=True, to='mainapp.TypeHair', verbose_name='Тип волос (ТОЛЬКО ДЛЯ ВОЛОС)'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_product',
            field=models.ManyToManyField(blank=True, to='mainapp.TypeProduct', verbose_name='Тип продукта (ТОЛЬКО ДЛЯ ТЕЛА)'),
        ),
        migrations.AddField(
            model_name='product',
            name='type_skin',
            field=models.ManyToManyField(blank=True, to='mainapp.TypeSkin', verbose_name='Тип кожи (ТОЛЬКО ДЛЯ ЛИЦА)'),
        ),
    ]
